# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stringmul.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstringmul.proto\x12\tstringmul\")\n\rStringRequest\x12\x0b\n\x03str\x18\x01 \x01(\t\x12\x0b\n\x03num\x18\x02 \x01(\x05\"\x1e\n\x0bStringArray\x12\x0f\n\x07strings\x18\x01 \x03(\t2K\n\tStringMul\x12>\n\x08Multiply\x12\x18.stringmul.StringRequest\x1a\x16.stringmul.StringArray\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stringmul_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STRINGREQUEST._serialized_start=30
  _STRINGREQUEST._serialized_end=71
  _STRINGARRAY._serialized_start=73
  _STRINGARRAY._serialized_end=103
  _STRINGMUL._serialized_start=105
  _STRINGMUL._serialized_end=180
# @@protoc_insertion_point(module_scope)
