# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import stringmul_pb2 as stringmul__pb2


class StringMulStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Multiply = channel.unary_unary(
                '/stringmul.StringMul/Multiply',
                request_serializer=stringmul__pb2.StringRequest.SerializeToString,
                response_deserializer=stringmul__pb2.StringArray.FromString,
                )


class StringMulServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Multiply(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StringMulServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Multiply': grpc.unary_unary_rpc_method_handler(
                    servicer.Multiply,
                    request_deserializer=stringmul__pb2.StringRequest.FromString,
                    response_serializer=stringmul__pb2.StringArray.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stringmul.StringMul', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StringMul(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Multiply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stringmul.StringMul/Multiply',
            stringmul__pb2.StringRequest.SerializeToString,
            stringmul__pb2.StringArray.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
