# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\ncalculator\">\n\x0f\x41\x64\x64itionRequest\x12\x14\n\x0c\x66irst_number\x18\x01 \x01(\x05\x12\x15\n\rsecond_number\x18\x02 \x01(\x05\"\x18\n\x06Result\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32K\n\nCalculator\x12=\n\x08\x41\x64\x64ition\x12\x1b.calculator.AdditionRequest\x1a\x12.calculator.Result\"\x00\x42HZFgithub.com/NaseerLodge/CloudNativeCourse/labs/final_project/calculatorb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZFgithub.com/NaseerLodge/CloudNativeCourse/labs/final_project/calculator'
  _ADDITIONREQUEST._serialized_start=32
  _ADDITIONREQUEST._serialized_end=94
  _RESULT._serialized_start=96
  _RESULT._serialized_end=120
  _CALCULATOR._serialized_start=122
  _CALCULATOR._serialized_end=197
# @@protoc_insertion_point(module_scope)
